application:
  name: commentservice
  project: appwish
  cloud_region: aws/eu-west-3
  publicly_accessible: true
databases:
  - type: postgresql
    version: "11.5"
    name: my-postgresql
routers:
  - name: main
    routes:
      - application_name: commentservice
        paths:
          - /*